version: "3.9"
services:
  mxchip-service:
    build: ./service
    ports:
      - "8081:3000"
    environment:
      MONGODB: mongodb://root:${MONGDBPASSWORD}@192.168.1.18:27017/mxchip?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
      PORT: 3000
      CORSORIGIN: http://hertogen.synology.me:8080

  mxchip-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "/volume1/docker/mxchip-mongo:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGDBPASSWORD}

  mxchip-app:
    build: ./app
    ports:
      - "8080:80"