on: [push]
name: Deploy to NAS
jobs:
  build-and-deploy:
    runs-on: self-hosted
    env: 
      MONGODB: ${{ secrets.MONGODB }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build app
      working-directory: ./app
      run: |
        npm ci
        npm run build:production
    - name: Build the docker-compose stack
      run: docker-compose up -d