on: [push]
name: Deploy azure ARM
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - run: docker login --username berthertogen --password ${{ secrets.DOCKER_PAT }}
    - run: docker build -t berthertogen/mxchip-service:latest ./service
    - run: docker push berthertogen/mxchip-service:latest