on: [push]
name: Deploy to NAS
jobs:
  build-and-deploy:
    runs-on: self-hosted
    env: 
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose up --build --detach