on: [push]
name: Deploy azure ARM
jobs:
  build-and-deploy:
    runs-on: self-hosted
    env: 
      MONGODB: ${{ secrets.MONGODB }}
    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose up -d
    # - run: docker login --username berthertogen --password ${{ secrets.DOCKER_PAT }}
    # - run: docker build -t berthertogen/mxchip-service:latest ./service
    # - run: docker push berthertogen/mxchip-service:latest
    # - run: docker pull berthertogen/mxchip-service:latest
    # - run: docker stop berthertogen-mxchip-service1
    # - run: docker stop berthertogen-mxchip-service1